=== BackupTheBerlios/genaro/PruebasDTecnologia/C_almohadilla/GladeYXml/conversacion.dtd
<!ELEMENT conversacion (para,de,mensajes)>
	<!ELEMENT para (#PCDATA)>
	<!ELEMENT de (#PCDATA)>
	<!ELEMENT mensajes (mensaje*)>
		<!ELEMENT mensaje (titulo,contenido)>
			<!ATTLIST mensaje numero ID #REQUIRED>
			<!ELEMENT titulo (#PCDATA)>
			<!ELEMENT contenido (#PCDATA)>

=== BackupTheBerlios/genaro/PruebasDTecnologia/C_almohadilla/GladeYXml/ej_conversacion.xml
<?xml version="1.0"?>
<!DOCTYPE conversacion SYSTEM "conversacion.dtd">
<c:conversacion xmlns:c="http://genaro.berlios.de/">
	<c:para>Paco</c:para>
	<c:de>Loli</c:de>
	<c:mensajes>
		<c:mensaje numero="msj1">
			<c:titulo>Compra el pan</c:titulo>
			<c:contenido>Pues eso Paquito, que te compres el pan</c:contenido>
		</c:mensaje>
                <c:mensaje numero="msj2">
			<c:titulo>Vengo tarde a cenar</c:titulo>
			<c:contenido>Pues eso Paquito, que me esperes porfi :p</c:contenido>
		</c:mensaje>
	</c:mensajes>
</c:conversacion>
